# config.toml

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#00c4ff"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"

